#ifndef RESOURCE_DEFS_H
#define RESOURCE_DEFS_H


#define  account_colors_bank  0
#define  account_colors_offset  0
#define  account_colors_length  6144
#define  account_patterns_bank  0
#define  account_patterns_offset  6144
#define  account_patterns_length  6144
#define  account_sprite_patterns_bank  1
#define  account_sprite_patterns_offset  4096
#define  account_sprite_patterns_length  176
#define  account_sprites_bank  1
#define  account_sprites_offset  4272
#define  account_sprites_length  24
#define  account_text_bank  1
#define  account_text_offset  4296
#define  account_text_length  704
#define  beetle_colors_bank  1
#define  beetle_colors_offset  5000
#define  beetle_colors_length  16
#define  beetle_nametable_bank  1
#define  beetle_nametable_offset  5016
#define  beetle_nametable_length  1536
#define  beetle_patt0_bank  1
#define  beetle_patt0_offset  6552
#define  beetle_patt0_length  1024
#define  beetle_patt1_bank  1
#define  beetle_patt1_offset  7576
#define  beetle_patt1_length  1024
#define  beetle_patt2_bank  2
#define  beetle_patt2_offset  408
#define  beetle_patt2_length  1024
#define  beetle_patt3_bank  2
#define  beetle_patt3_offset  1432
#define  beetle_patt3_length  1024
#define  beetle_patt4_bank  2
#define  beetle_patt4_offset  2456
#define  beetle_patt4_length  1024
#define  beetle_patt5_bank  2
#define  beetle_patt5_offset  3480
#define  beetle_patt5_length  1024
#define  beetle_patt6_bank  2
#define  beetle_patt6_offset  4504
#define  beetle_patt6_length  1024
#define  beetle_patt7_bank  2
#define  beetle_patt7_offset  5528
#define  beetle_patt7_length  1024
#define  beetle_shop_colors_bank  2
#define  beetle_shop_colors_offset  6552
#define  beetle_shop_colors_length  32
#define  beetle_shop_nametable_bank  2
#define  beetle_shop_nametable_offset  6584
#define  beetle_shop_nametable_length  216
#define  beetle_shop_patterns_bank  2
#define  beetle_shop_patterns_offset  6800
#define  beetle_shop_patterns_length  896
#define  beetle_sprites_bank  2
#define  beetle_sprites_offset  7696
#define  beetle_sprites_length  736
#define  boss_battle_colors_bank  3
#define  boss_battle_colors_offset  240
#define  boss_battle_colors_length  6144
#define  boss_battle_patterns_bank  3
#define  boss_battle_patterns_offset  6384
#define  boss_battle_patterns_length  6144
#define  brooklyn_bldg_colors_bank  4
#define  brooklyn_bldg_colors_offset  4336
#define  brooklyn_bldg_colors_length  6144
#define  brooklyn_bldg_patterns_bank  5
#define  brooklyn_bldg_patterns_offset  2288
#define  brooklyn_bldg_patterns_length  6144
#define  drive_colors_bank  6
#define  drive_colors_offset  240
#define  drive_colors_length  16
#define  drive_nametable_bank  6
#define  drive_nametable_offset  256
#define  drive_nametable_length  1536
#define  drive_patt0_bank  6
#define  drive_patt0_offset  1792
#define  drive_patt0_length  1024
#define  drive_patt1_bank  6
#define  drive_patt1_offset  2816
#define  drive_patt1_length  1024
#define  drive_patt2_bank  6
#define  drive_patt2_offset  3840
#define  drive_patt2_length  1024
#define  drive_patt3_bank  6
#define  drive_patt3_offset  4864
#define  drive_patt3_length  1024
#define  drive_patt4_bank  6
#define  drive_patt4_offset  5888
#define  drive_patt4_length  1024
#define  drive_patt5_bank  6
#define  drive_patt5_offset  6912
#define  drive_patt5_length  1024
#define  drive_patt6_bank  6
#define  drive_patt6_offset  7936
#define  drive_patt6_length  1024
#define  drive_patt7_bank  7
#define  drive_patt7_offset  768
#define  drive_patt7_length  1024
#define  drive_sprites_bank  7
#define  drive_sprites_offset  1792
#define  drive_sprites_length  736
#define  font_bank  7
#define  font_offset  2528
#define  font_length  760
#define  fx_bank  7
#define  fx_offset  3288
#define  fx_length  954
#define  gbhq_bldg_colors_bank  7
#define  gbhq_bldg_colors_offset  4242
#define  gbhq_bldg_colors_length  6144
#define  gbhq_bldg_patterns_bank  8
#define  gbhq_bldg_patterns_offset  2194
#define  gbhq_bldg_patterns_length  6144
#define  glowing_skull_sprites_bank  9
#define  glowing_skull_sprites_offset  146
#define  glowing_skull_sprites_length  128
#define  hearse_shop_colors_bank  9
#define  hearse_shop_colors_offset  274
#define  hearse_shop_colors_length  32
#define  hearse_shop_nametable_bank  9
#define  hearse_shop_nametable_offset  306
#define  hearse_shop_nametable_length  216
#define  hearse_shop_patterns_bank  9
#define  hearse_shop_patterns_offset  522
#define  hearse_shop_patterns_length  768
#define  house_bldg_colors_bank  9
#define  house_bldg_colors_offset  1290
#define  house_bldg_colors_length  6144
#define  house_bldg_patterns_bank  9
#define  house_bldg_patterns_offset  7434
#define  house_bldg_patterns_length  6144
#define  introscroll_bank  10
#define  introscroll_offset  5386
#define  introscroll_length  166
#define  logo_colors_bank  10
#define  logo_colors_offset  5552
#define  logo_colors_length  32
#define  logo_music_bank  10
#define  logo_music_offset  5584
#define  logo_music_length  754
#define  logo_nametable00_bank  10
#define  logo_nametable00_offset  6338
#define  logo_nametable00_length  768
#define  logo_patterns_bank  10
#define  logo_patterns_offset  7106
#define  logo_patterns_length  320
#define  lost_bank  10
#define  lost_offset  7426
#define  lost_length  193
#define  lyrics_bank  10
#define  lyrics_offset  7619
#define  lyrics_length  1437
#define  main_sprites_bank  11
#define  main_sprites_offset  864
#define  main_sprites_length  1712
#define  maintheme_bank  11
#define  maintheme_offset  2576
#define  maintheme_length  1486
#define  map_colors_bank  11
#define  map_colors_offset  4062
#define  map_colors_length  6144
#define  map_nw_colors_bank  12
#define  map_nw_colors_offset  2014
#define  map_nw_colors_length  2048
#define  map_nw_nametable00_bank  12
#define  map_nw_nametable00_offset  4062
#define  map_nw_nametable00_length  1408
#define  map_nw_nametable01_bank  12
#define  map_nw_nametable01_offset  5470
#define  map_nw_nametable01_length  925
#define  map_nw_patterns_bank  12
#define  map_nw_patterns_offset  6395
#define  map_nw_patterns_length  2048
#define  map_patterns_bank  13
#define  map_patterns_offset  251
#define  map_patterns_length  6144
#define  office_bldg_colors_bank  13
#define  office_bldg_colors_offset  6395
#define  office_bldg_colors_length  6144
#define  office_bldg_patterns_bank  14
#define  office_bldg_patterns_offset  4347
#define  office_bldg_patterns_length  6144
#define  scrollfont_patterns_bank  15
#define  scrollfont_patterns_offset  2299
#define  scrollfont_patterns_length  6144
#define  sedgewick_bldg_colors_bank  16
#define  sedgewick_bldg_colors_offset  251
#define  sedgewick_bldg_colors_length  6144
#define  sedgewick_bldg_patterns_bank  16
#define  sedgewick_bldg_patterns_offset  6395
#define  sedgewick_bldg_patterns_length  6144
#define  shop_font_patterns_bank  17
#define  shop_font_patterns_offset  4347
#define  shop_font_patterns_length  512
#define  shop_sprite_patterns_bank  17
#define  shop_sprite_patterns_offset  4859
#define  shop_sprite_patterns_length  704
#define  shout_bank  17
#define  shout_offset  5563
#define  shout_length  18231
#define  skull_sprites_bank  19
#define  skull_sprites_offset  7410
#define  skull_sprites_length  128
#define  slimed_bank  19
#define  slimed_offset  7538
#define  slimed_length  15776
#define  sportscar_colors_bank  21
#define  sportscar_colors_offset  6930
#define  sportscar_colors_length  15
#define  sportscar_nametable_bank  21
#define  sportscar_nametable_offset  6945
#define  sportscar_nametable_length  1536
#define  sportscar_patt0_bank  22
#define  sportscar_patt0_offset  289
#define  sportscar_patt0_length  1024
#define  sportscar_patt1_bank  22
#define  sportscar_patt1_offset  1313
#define  sportscar_patt1_length  1024
#define  sportscar_patt2_bank  22
#define  sportscar_patt2_offset  2337
#define  sportscar_patt2_length  1024
#define  sportscar_patt3_bank  22
#define  sportscar_patt3_offset  3361
#define  sportscar_patt3_length  1024
#define  sportscar_patt4_bank  22
#define  sportscar_patt4_offset  4385
#define  sportscar_patt4_length  1024
#define  sportscar_patt5_bank  22
#define  sportscar_patt5_offset  5409
#define  sportscar_patt5_length  1024
#define  sportscar_patt6_bank  22
#define  sportscar_patt6_offset  6433
#define  sportscar_patt6_length  1024
#define  sportscar_patt7_bank  22
#define  sportscar_patt7_offset  7457
#define  sportscar_patt7_length  1024
#define  sportscar_shop_colors_bank  23
#define  sportscar_shop_colors_offset  289
#define  sportscar_shop_colors_length  32
#define  sportscar_shop_nametable_bank  23
#define  sportscar_shop_nametable_offset  321
#define  sportscar_shop_nametable_length  216
#define  sportscar_shop_patterns_bank  23
#define  sportscar_shop_patterns_offset  537
#define  sportscar_shop_patterns_length  704
#define  sportscar_sprites_bank  23
#define  sportscar_sprites_offset  1241
#define  sportscar_sprites_length  736
#define  stay_puft_sprite_patterns_bank  23
#define  stay_puft_sprite_patterns_offset  1977
#define  stay_puft_sprite_patterns_length  1440
#define  suburban_bldg_colors_bank  23
#define  suburban_bldg_colors_offset  3417
#define  suburban_bldg_colors_length  6144
#define  suburban_bldg_patterns_bank  24
#define  suburban_bldg_patterns_offset  1369
#define  suburban_bldg_patterns_length  6144
#define  themesong_bank  24
#define  themesong_offset  7513
#define  themesong_length  9516
#define  title_colors_bank  26
#define  title_colors_offset  645
#define  title_colors_length  6144
#define  title_patterns_bank  26
#define  title_patterns_offset  6789
#define  title_patterns_length  6144
#define  title_sprite_attributes_bank  27
#define  title_sprite_attributes_offset  4741
#define  title_sprite_attributes_length  128
#define  title_sprite_patterns_bank  27
#define  title_sprite_patterns_offset  4869
#define  title_sprite_patterns_length  512
#define  wagon_colors_bank  27
#define  wagon_colors_offset  5381
#define  wagon_colors_length  16
#define  wagon_nametable_bank  27
#define  wagon_nametable_offset  5397
#define  wagon_nametable_length  1536
#define  wagon_patt0_bank  27
#define  wagon_patt0_offset  6933
#define  wagon_patt0_length  1024
#define  wagon_patt1_bank  27
#define  wagon_patt1_offset  7957
#define  wagon_patt1_length  1024
#define  wagon_patt2_bank  28
#define  wagon_patt2_offset  789
#define  wagon_patt2_length  1024
#define  wagon_patt3_bank  28
#define  wagon_patt3_offset  1813
#define  wagon_patt3_length  1024
#define  wagon_patt4_bank  28
#define  wagon_patt4_offset  2837
#define  wagon_patt4_length  1024
#define  wagon_patt5_bank  28
#define  wagon_patt5_offset  3861
#define  wagon_patt5_length  1024
#define  wagon_patt6_bank  28
#define  wagon_patt6_offset  4885
#define  wagon_patt6_length  1024
#define  wagon_patt7_bank  28
#define  wagon_patt7_offset  5909
#define  wagon_patt7_length  1024
#define  wagon_shop_colors_bank  28
#define  wagon_shop_colors_offset  6933
#define  wagon_shop_colors_length  32
#define  wagon_shop_nametable_bank  28
#define  wagon_shop_nametable_offset  6965
#define  wagon_shop_nametable_length  216
#define  wagon_shop_patterns_bank  28
#define  wagon_shop_patterns_offset  7181
#define  wagon_shop_patterns_length  800
#define  wagon_sprites_bank  28
#define  wagon_sprites_offset  7981
#define  wagon_sprites_length  736
#define  won_bank  29
#define  won_offset  525
#define  won_length  320
#define  wonwon_bank  29
#define  wonwon_offset  845
#define  wonwon_length  352
#define  zuul_colors_bank  29
#define  zuul_colors_offset  1197
#define  zuul_colors_length  2048
#define  zuul_nametable00_bank  29
#define  zuul_nametable00_offset  3245
#define  zuul_nametable00_length  5120
#define  zuul_patterns_bank  30
#define  zuul_patterns_offset  173
#define  zuul_patterns_length  2048

#endif
